# Generated by Django 3.2.14 on 2022-08-10 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('health_detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='详情记录')),
                ('tag', models.IntegerField(choices=[(1, '轻微'), (2, '中等'), (2, '严重')], default=1, verbose_name='疼痛等级')),
                ('magicbox_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo', verbose_name='创建人')),
            ],
        ),
    ]
