# Generated by Django 3.2.14 on 2022-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_healthinfo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinfo',
            name='text',
            field=models.IntegerField(choices=[(1, '轻微'), (2, '中等'), (3, '严重')], default=3, error_messages={'invalid': '标签选择错误', 'required': '标签必须选择'}, verbose_name='疼痛等级'),
        ),
    ]
